# Generated by Django 4.1.2 on 2022-10-08 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('a_time', models.TimeField()),
                ('d_time', models.TimeField()),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roommanage.classroom')),
            ],
        ),
    ]
