# Generated by Django 4.1.2 on 2022-10-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanage', '0002_bookclassroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclassroom',
            name='reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
