# Generated by Django 4.1.2 on 2022-11-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanage', '0003_bookclassroom_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine', models.FileField(null=True, upload_to='routine/')),
            ],
        ),
    ]
