# Generated by Django 4.1.2 on 2022-11-15 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanage', '0004_routine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.IntegerField(default=50, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
